sonar.projectKey=georgiahills
sonar.organization=georgiahills-org
sonar.sources=.
sonar.exclusions=node_modules/**, dist/**, tests/**, **/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
