export type SecondaryPage = {
  slug: string;
  lang: "en" | "ar";
  dir: "ltr" | "rtl";
  title: string;
  description: string;
  heading: string;
  body: string;
  canonical: string;
  pairedSlug?: string;
  ctaPrimaryLabel: string;
  ctaPrimaryHref: string;
  ctaSecondaryLabel: string;
  ctaSecondaryHref: string;
};

export const secondaryPages: SecondaryPage[] = [
  {
    slug: "about",
    lang: "en",
    dir: "ltr",
    title: "About Georgia Hills | Private Travel Experts",
    description: "Learn about Georgia Hills and our premium private transport services for families and GCC travelers.",
    heading: "About Georgia Hills",
    body: "We provide private driver services and curated itineraries in Georgia with a focus on comfort, safety, and Arabic-friendly support.",
    canonical: "https://georgiahills.com/about.html",
    pairedSlug: "about-ar",
    ctaPrimaryLabel: "Book Your Trip",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "Contact on WhatsApp",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "about-ar",
    lang: "ar",
    dir: "rtl",
    title: "من نحن | Georgia Hills",
    description: "تعرف على Georgia Hills وخدمات النقل الخاصة الفاخرة للمسافرين العرب في جورجيا.",
    heading: "من نحن",
    body: "نقدم خدمات سائق خاص وبرامج سياحية مدروسة في جورجيا مع تركيز على الراحة والأمان والدعم العربي.",
    canonical: "https://georgiahills.com/about-ar.html",
    pairedSlug: "about",
    ctaPrimaryLabel: "احجز رحلتك",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "تواصل واتساب",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "services",
    lang: "en",
    dir: "ltr",
    title: "Services | Private Driver & Tours in Georgia",
    description: "Explore private driver, airport transfer, and custom tour services across Georgia.",
    heading: "Our Services",
    body: "From airport pickups to full multi-day private tours, we provide premium transport solutions with transparent pricing.",
    canonical: "https://georgiahills.com/services.html",
    pairedSlug: "services-ar",
    ctaPrimaryLabel: "Request a Quote",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "View Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "services-ar",
    lang: "ar",
    dir: "rtl",
    title: "الخدمات | سائق خاص وجولات في جورجيا",
    description: "اكتشف خدمات السائق الخاص والاستقبال من المطار والبرامج السياحية المخصصة في جورجيا.",
    heading: "خدماتنا",
    body: "من الاستقبال في المطار إلى الجولات الخاصة متعددة الأيام، نقدم حلول نقل فاخرة بأسعار واضحة.",
    canonical: "https://georgiahills.com/services-ar.html",
    pairedSlug: "services",
    ctaPrimaryLabel: "اطلب عرض سعر",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "استعرض الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "guide",
    lang: "en",
    dir: "ltr",
    title: "Travel Guide Georgia | Tips for GCC Travelers",
    description: "Practical travel guide for Georgia including weather, routes, and family-friendly planning tips.",
    heading: "Georgia Travel Guide",
    body: "Plan your trip with local insights on best seasons, routes, and practical guidance for families and first-time visitors.",
    canonical: "https://georgiahills.com/guide.html",
    pairedSlug: "guide-ar",
    ctaPrimaryLabel: "Start Planning",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "View Itineraries",
    ctaSecondaryHref: "/itineraries-hub.html"
  },
  {
    slug: "guide-ar",
    lang: "ar",
    dir: "rtl",
    title: "دليل السفر إلى جورجيا | نصائح للمسافرين العرب",
    description: "دليل عملي للسفر إلى جورجيا يشمل الطقس والمسارات ونصائح للعائلات.",
    heading: "دليل السفر إلى جورجيا",
    body: "خطط رحلتك بسهولة مع معلومات محلية حول أفضل المواسم والمسارات والنصائح العملية للعائلات.",
    canonical: "https://georgiahills.com/guide-ar.html",
    pairedSlug: "guide",
    ctaPrimaryLabel: "ابدأ التخطيط",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "استعرض البرامج",
    ctaSecondaryHref: "/itineraries-hub-ar.html"
  },
  {
    slug: "contact",
    lang: "en",
    dir: "ltr",
    title: "Contact Georgia Hills | Fast WhatsApp Support",
    description: "Contact Georgia Hills for private driver bookings, itinerary planning, and premium travel support.",
    heading: "Contact Us",
    body: "Reach our team for quotes, route planning, and custom travel requirements. We usually reply within minutes on WhatsApp.",
    canonical: "https://georgiahills.com/contact.html",
    pairedSlug: "contact-ar",
    ctaPrimaryLabel: "Book Now",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "WhatsApp Support",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "contact-ar",
    lang: "ar",
    dir: "rtl",
    title: "اتصل بنا | Georgia Hills",
    description: "تواصل مع Georgia Hills للحجز والتخطيط السياحي والدعم السريع عبر واتساب.",
    heading: "اتصل بنا",
    body: "تواصل معنا لطلب عروض الأسعار وتخطيط المسارات والطلبات الخاصة. غالباً نرد خلال دقائق عبر واتساب.",
    canonical: "https://georgiahills.com/contact-ar.html",
    pairedSlug: "contact",
    ctaPrimaryLabel: "احجز الآن",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "دعم واتساب",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "destinations-hub",
    lang: "en",
    dir: "ltr",
    title: "Destinations in Georgia | Georgia Hills",
    description: "Top destinations in Georgia with private transport options and tailored itineraries.",
    heading: "Georgia Destinations",
    body: "Discover Tbilisi, Kazbegi, Batumi, and more with route planning designed for comfort and premium travel.",
    canonical: "https://georgiahills.com/destinations-hub.html",
    pairedSlug: "destinations-hub-ar",
    ctaPrimaryLabel: "Build Itinerary",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "View Guide",
    ctaSecondaryHref: "/guide.html"
  },
  {
    slug: "destinations-hub-ar",
    lang: "ar",
    dir: "rtl",
    title: "وجهات جورجيا | Georgia Hills",
    description: "أهم الوجهات السياحية في جورجيا مع خيارات نقل خاص وبرامج مخصصة.",
    heading: "وجهات جورجيا",
    body: "اكتشف تبليسي وكازبيجي وباتومي وغيرها مع تخطيط مسارات مناسب للراحة والسفر الفاخر.",
    canonical: "https://georgiahills.com/destinations-hub-ar.html",
    pairedSlug: "destinations-hub",
    ctaPrimaryLabel: "صمم برنامجك",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "استعرض الدليل",
    ctaSecondaryHref: "/guide-ar.html"
  },
  {
    slug: "tbilisi",
    lang: "en",
    dir: "ltr",
    title: "Tbilisi Tours with Private Driver | Georgia Hills",
    description: "Explore Tbilisi with a private driver, flexible schedule, and family-friendly pacing.",
    heading: "Tbilisi Private Tour",
    body: "Enjoy Old Tbilisi, viewpoints, and curated city experiences with premium transport and local expertise.",
    canonical: "https://georgiahills.com/tbilisi.html",
    pairedSlug: "tbilisi-ar",
    ctaPrimaryLabel: "Book Tbilisi Tour",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "All Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "tbilisi-ar",
    lang: "ar",
    dir: "rtl",
    title: "جولة تبليسي مع سائق خاص | Georgia Hills",
    description: "استكشف تبليسي مع سائق خاص وجدول مرن وتجربة مناسبة للعائلات.",
    heading: "جولة تبليسي الخاصة",
    body: "استمتع بوسط تبليسي القديم وأجمل الإطلالات مع نقل فاخر وخبرة محلية.",
    canonical: "https://georgiahills.com/tbilisi-ar.html",
    pairedSlug: "tbilisi",
    ctaPrimaryLabel: "احجز جولة تبليسي",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "كل الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "batumi",
    lang: "en",
    dir: "ltr",
    title: "Batumi Tours with Private Driver | Georgia Hills",
    description: "Premium Batumi tours with private transport, flexible timing, and personalized routes.",
    heading: "Batumi Private Tour",
    body: "Experience Batumi seafront, botanical garden, and nearby attractions with comfort-first transport.",
    canonical: "https://georgiahills.com/batumi.html",
    pairedSlug: "batumi-ar",
    ctaPrimaryLabel: "Book Batumi Tour",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "All Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "batumi-ar",
    lang: "ar",
    dir: "rtl",
    title: "جولة باتومي مع سائق خاص | Georgia Hills",
    description: "برامج باتومي الخاصة مع نقل فاخر وجدول مرن ومسارات مخصصة.",
    heading: "جولة باتومي الخاصة",
    body: "استمتع بكورنيش باتومي والحديقة النباتية والوجهات القريبة مع نقل مريح.",
    canonical: "https://georgiahills.com/batumi-ar.html",
    pairedSlug: "batumi",
    ctaPrimaryLabel: "احجز جولة باتومي",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "كل الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "kazbegi",
    lang: "en",
    dir: "ltr",
    title: "Kazbegi Day Trip with Private Driver | Georgia Hills",
    description: "Private Kazbegi trips via scenic routes with stops tailored to your travel style.",
    heading: "Kazbegi Private Trip",
    body: "Travel to the Caucasus mountains with a private driver and carefully planned scenic stops.",
    canonical: "https://georgiahills.com/kazbegi.html",
    pairedSlug: "kazbegi-ar",
    ctaPrimaryLabel: "Book Kazbegi Trip",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "All Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "kazbegi-ar",
    lang: "ar",
    dir: "rtl",
    title: "رحلة كازبيجي مع سائق خاص | Georgia Hills",
    description: "رحلات كازبيجي الخاصة عبر طرق جبلية مميزة مع محطات حسب رغبتك.",
    heading: "رحلة كازبيجي الخاصة",
    body: "انطلق إلى جبال القوقاز مع سائق خاص ومحطات مناظر طبيعية مخططة بعناية.",
    canonical: "https://georgiahills.com/kazbegi-ar.html",
    pairedSlug: "kazbegi",
    ctaPrimaryLabel: "احجز رحلة كازبيجي",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "كل الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "martvili",
    lang: "en",
    dir: "ltr",
    title: "Martvili Canyon Tour | Georgia Hills",
    description: "Visit Martvili Canyon with private transport and curated stops for families and couples.",
    heading: "Martvili Canyon Tour",
    body: "Explore Martvili's natural beauty with convenient private transport and flexible timing.",
    canonical: "https://georgiahills.com/martvili.html",
    pairedSlug: "martvili-ar",
    ctaPrimaryLabel: "Book Martvili Tour",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "All Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "martvili-ar",
    lang: "ar",
    dir: "rtl",
    title: "جولة مارتفيلي | Georgia Hills",
    description: "زيارة وادي مارتفيلي مع نقل خاص ومحطات مناسبة للعائلات والأزواج.",
    heading: "جولة مارتفيلي",
    body: "اكتشف جمال مارتفيلي الطبيعي مع نقل خاص وتوقيت مرن يناسب رحلتك.",
    canonical: "https://georgiahills.com/martvili-ar.html",
    pairedSlug: "martvili",
    ctaPrimaryLabel: "احجز جولة مارتفيلي",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "كل الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "signagi",
    lang: "en",
    dir: "ltr",
    title: "Signagi Tour with Private Driver | Georgia Hills",
    description: "Private Signagi tour with views, wine-region routes, and premium comfort.",
    heading: "Signagi Private Tour",
    body: "Visit Signagi and Kakheti highlights with a private driver and smooth day planning.",
    canonical: "https://georgiahills.com/signagi.html",
    pairedSlug: "signagi-ar",
    ctaPrimaryLabel: "Book Signagi Tour",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "All Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "signagi-ar",
    lang: "ar",
    dir: "rtl",
    title: "جولة سيغناغي مع سائق خاص | Georgia Hills",
    description: "جولة سيغناغي الخاصة مع إطلالات رائعة ومسارات كاخيتي المميزة.",
    heading: "جولة سيغناغي الخاصة",
    body: "زر سيغناغي وأبرز معالم كاخيتي مع سائق خاص وتخطيط يوم مريح.",
    canonical: "https://georgiahills.com/signagi-ar.html",
    pairedSlug: "signagi",
    ctaPrimaryLabel: "احجز جولة سيغناغي",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "كل الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "halal-travel-hub",
    lang: "en",
    dir: "ltr",
    title: "Halal Travel in Georgia | Georgia Hills",
    description: "Halal-friendly Georgia itineraries with prayer stops, halal dining, and private transport.",
    heading: "Halal Travel Hub",
    body: "Plan halal-focused trips across Georgia with trusted dining options, prayer-friendly timing, and private drivers.",
    canonical: "https://georgiahills.com/halal-travel-hub.html",
    pairedSlug: "halal-travel-hub-ar",
    ctaPrimaryLabel: "Get Halal Quote",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "View Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "halal-travel-hub-ar",
    lang: "ar",
    dir: "rtl",
    title: "السفر الحلال في جورجيا | Georgia Hills",
    description: "برامج سفر حلال في جورجيا مع محطات صلاة وخيارات مطاعم مناسبة ونقل خاص.",
    heading: "مركز السفر الحلال",
    body: "خطط رحلتك الحلال في جورجيا مع خيارات موثوقة للمطاعم ومحطات الصلاة وخدمة سائق خاص.",
    canonical: "https://georgiahills.com/halal-travel-hub-ar.html",
    pairedSlug: "halal-travel-hub",
    ctaPrimaryLabel: "اطلب عرض حلال",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "استعرض الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "family-travel-hub",
    lang: "en",
    dir: "ltr",
    title: "Family Travel Georgia | Georgia Hills",
    description: "Family-friendly Georgia tours with comfortable pacing, private transport, and trusted support.",
    heading: "Family Travel Hub",
    body: "Explore Georgia with child-friendly pacing, smart route planning, and private vehicles designed for family comfort.",
    canonical: "https://georgiahills.com/family-travel-hub.html",
    pairedSlug: "family-travel-hub-ar",
    ctaPrimaryLabel: "Plan Family Trip",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "View Guide",
    ctaSecondaryHref: "/guide.html"
  },
  {
    slug: "family-travel-hub-ar",
    lang: "ar",
    dir: "rtl",
    title: "السفر العائلي إلى جورجيا | Georgia Hills",
    description: "برامج سياحية عائلية في جورجيا مع نقل خاص وجدول مريح ودعم موثوق.",
    heading: "مركز السفر العائلي",
    body: "استمتع برحلة عائلية إلى جورجيا مع تخطيط ذكي للمسارات ووتيرة مناسبة للأطفال ونقل خاص.",
    canonical: "https://georgiahills.com/family-travel-hub-ar.html",
    pairedSlug: "family-travel-hub",
    ctaPrimaryLabel: "خطط رحلة عائلية",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "استعرض الدليل",
    ctaSecondaryHref: "/guide-ar.html"
  },
  {
    slug: "itineraries-hub",
    lang: "en",
    dir: "ltr",
    title: "Georgia Itineraries | Georgia Hills",
    description: "Ready-to-customize Georgia itineraries for families, couples, and premium travelers.",
    heading: "Itineraries Hub",
    body: "Choose from curated Georgia itineraries and customize durations, routes, and experiences with private transport.",
    canonical: "https://georgiahills.com/itineraries-hub.html",
    pairedSlug: "itineraries-hub-ar",
    ctaPrimaryLabel: "Build Itinerary",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "Talk to Planner",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "itineraries-hub-ar",
    lang: "ar",
    dir: "rtl",
    title: "برامج جورجيا السياحية | Georgia Hills",
    description: "برامج جاهزة وقابلة للتخصيص في جورجيا للعائلات والأزواج والمسافرين الفاخرين.",
    heading: "مركز البرامج السياحية",
    body: "اختر من برامج جورجيا المصممة بعناية ثم خصص المدة والمسار والتجارب مع خدمة نقل خاصة.",
    canonical: "https://georgiahills.com/itineraries-hub-ar.html",
    pairedSlug: "itineraries-hub",
    ctaPrimaryLabel: "صمم برنامجك",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "تواصل مع المخطط",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "safety-hub",
    lang: "en",
    dir: "ltr",
    title: "Georgia Travel Safety | Georgia Hills",
    description: "Safety guidance for traveling in Georgia with practical tips, transport support, and local insights.",
    heading: "Safety Hub",
    body: "Get practical safety guidance on routes, city movement, family travel, and day planning in Georgia.",
    canonical: "https://georgiahills.com/safety-hub.html",
    pairedSlug: "safety-hub-ar",
    ctaPrimaryLabel: "Plan Safe Trip",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "Contact Support",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "safety-hub-ar",
    lang: "ar",
    dir: "rtl",
    title: "السلامة أثناء السفر في جورجيا | Georgia Hills",
    description: "إرشادات السلامة للسفر في جورجيا مع نصائح عملية ودعم نقل وخبرة محلية.",
    heading: "مركز السلامة",
    body: "تعرف على إرشادات السلامة العملية للمسارات والتنقل داخل المدن والسفر العائلي في جورجيا.",
    canonical: "https://georgiahills.com/safety-hub-ar.html",
    pairedSlug: "safety-hub",
    ctaPrimaryLabel: "خطط رحلة آمنة",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "تواصل مع الدعم",
    ctaSecondaryHref: "https://wa.me/995579088537"
  },
  {
    slug: "honeymoon",
    lang: "en",
    dir: "ltr",
    title: "Honeymoon in Georgia | Georgia Hills",
    description: "Romantic honeymoon itineraries in Georgia with private transport and premium comfort.",
    heading: "Honeymoon Travel",
    body: "Enjoy romantic Georgia routes with private driver service, scenic stays, and flexible day planning.",
    canonical: "https://georgiahills.com/honeymoon.html",
    pairedSlug: "honeymoon-ar",
    ctaPrimaryLabel: "Get Honeymoon Quote",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "View Destinations",
    ctaSecondaryHref: "/destinations-hub.html"
  },
  {
    slug: "honeymoon-ar",
    lang: "ar",
    dir: "rtl",
    title: "شهر العسل في جورجيا | Georgia Hills",
    description: "برامج شهر عسل رومانسية في جورجيا مع نقل خاص وراحة فاخرة.",
    heading: "سفر شهر العسل",
    body: "استمتع بمسارات رومانسية في جورجيا مع خدمة سائق خاص وإقامة مميزة وتخطيط يوم مرن.",
    canonical: "https://georgiahills.com/honeymoon-ar.html",
    pairedSlug: "honeymoon",
    ctaPrimaryLabel: "احصل على عرض شهر العسل",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "استعرض الوجهات",
    ctaSecondaryHref: "/destinations-hub-ar.html"
  },
  {
    slug: "privacy",
    lang: "en",
    dir: "ltr",
    title: "Privacy Policy | Georgia Hills",
    description: "Privacy policy for Georgia Hills lead forms, WhatsApp communication, and data handling.",
    heading: "Privacy Policy",
    body: "We collect only booking-relevant details (name, contact, trip preferences) to provide quotes and support. We do not sell personal data. You can request data correction or deletion by contacting info@georgiahills.com.",
    canonical: "https://georgiahills.com/privacy.html",
    pairedSlug: "privacy-ar",
    ctaPrimaryLabel: "Contact Support",
    ctaPrimaryHref: "/contact.html",
    ctaSecondaryLabel: "Terms & Conditions",
    ctaSecondaryHref: "/terms.html"
  },
  {
    slug: "privacy-ar",
    lang: "ar",
    dir: "rtl",
    title: "سياسة الخصوصية | Georgia Hills",
    description: "سياسة الخصوصية الخاصة بجمع بيانات الحجز والتواصل عبر واتساب في Georgia Hills.",
    heading: "سياسة الخصوصية",
    body: "نجمع فقط بيانات مرتبطة بالحجز مثل الاسم ووسيلة التواصل وتفضيلات الرحلة لتقديم العرض والدعم. لا نقوم ببيع البيانات الشخصية. يمكنك طلب تعديل أو حذف بياناتك عبر info@georgiahills.com.",
    canonical: "https://georgiahills.com/privacy-ar.html",
    pairedSlug: "privacy",
    ctaPrimaryLabel: "تواصل مع الدعم",
    ctaPrimaryHref: "/contact-ar.html",
    ctaSecondaryLabel: "الشروط والأحكام",
    ctaSecondaryHref: "/terms-ar.html"
  },
  {
    slug: "terms",
    lang: "en",
    dir: "ltr",
    title: "Terms and Conditions | Georgia Hills",
    description: "Terms and booking conditions for private transport and travel planning services.",
    heading: "Terms and Conditions",
    body: "Quotes are confirmed after itinerary details are reviewed. Final pricing may vary by season, route changes, and availability. Service starts after written confirmation via WhatsApp or email.",
    canonical: "https://georgiahills.com/terms.html",
    pairedSlug: "terms-ar",
    ctaPrimaryLabel: "Booking Request",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "Cancellation Policy",
    ctaSecondaryHref: "/cancellation.html"
  },
  {
    slug: "terms-ar",
    lang: "ar",
    dir: "rtl",
    title: "الشروط والأحكام | Georgia Hills",
    description: "شروط وأحكام الحجز لخدمات النقل الخاص والتخطيط السياحي في جورجيا.",
    heading: "الشروط والأحكام",
    body: "يتم تأكيد العرض بعد مراجعة تفاصيل الرحلة. قد يتغير السعر النهائي حسب الموسم أو تعديل المسار أو التوفر. تبدأ الخدمة بعد تأكيد مكتوب عبر واتساب أو البريد الإلكتروني.",
    canonical: "https://georgiahills.com/terms-ar.html",
    pairedSlug: "terms",
    ctaPrimaryLabel: "طلب حجز",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "سياسة الإلغاء",
    ctaSecondaryHref: "/cancellation-ar.html"
  },
  {
    slug: "cancellation",
    lang: "en",
    dir: "ltr",
    title: "Cancellation Policy | Georgia Hills",
    description: "Cancellation and change policy for confirmed bookings.",
    heading: "Cancellation Policy",
    body: "Date and route changes are possible based on availability. For confirmed reservations, cancellation terms are provided in your final quote. Emergency-related changes are handled with priority support.",
    canonical: "https://georgiahills.com/cancellation.html",
    pairedSlug: "cancellation-ar",
    ctaPrimaryLabel: "Talk to Support",
    ctaPrimaryHref: "/contact.html",
    ctaSecondaryLabel: "Insurance Details",
    ctaSecondaryHref: "/insurance.html"
  },
  {
    slug: "cancellation-ar",
    lang: "ar",
    dir: "rtl",
    title: "سياسة الإلغاء | Georgia Hills",
    description: "سياسة الإلغاء وتعديل الحجوزات المؤكدة لدى Georgia Hills.",
    heading: "سياسة الإلغاء",
    body: "يمكن تعديل التاريخ أو المسار حسب التوفر. للحجوزات المؤكدة يتم توضيح بنود الإلغاء في العرض النهائي. الحالات الطارئة يتم التعامل معها بأولوية عالية.",
    canonical: "https://georgiahills.com/cancellation-ar.html",
    pairedSlug: "cancellation",
    ctaPrimaryLabel: "تواصل مع الدعم",
    ctaPrimaryHref: "/contact-ar.html",
    ctaSecondaryLabel: "تفاصيل التأمين",
    ctaSecondaryHref: "/insurance-ar.html"
  },
  {
    slug: "insurance",
    lang: "en",
    dir: "ltr",
    title: "Insurance and Safety Coverage | Georgia Hills",
    description: "Operational safety and insurance disclosure for private transport services.",
    heading: "Insurance and Safety",
    body: "Vehicles are operated under local regulatory requirements. Insurance scope and included protections are disclosed in your confirmed booking summary.",
    canonical: "https://georgiahills.com/insurance.html",
    pairedSlug: "insurance-ar",
    ctaPrimaryLabel: "Request Quote",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "Licensing Info",
    ctaSecondaryHref: "/licensing.html"
  },
  {
    slug: "insurance-ar",
    lang: "ar",
    dir: "rtl",
    title: "التأمين والسلامة | Georgia Hills",
    description: "توضيح نطاق التأمين والسلامة التشغيلية لخدمات النقل الخاص.",
    heading: "التأمين والسلامة",
    body: "يتم تشغيل المركبات وفق المتطلبات التنظيمية المحلية. يتم توضيح نطاق التأمين والحماية المتاحة ضمن ملخص الحجز المؤكد.",
    canonical: "https://georgiahills.com/insurance-ar.html",
    pairedSlug: "insurance",
    ctaPrimaryLabel: "اطلب عرض سعر",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "معلومات الترخيص",
    ctaSecondaryHref: "/licensing-ar.html"
  },
  {
    slug: "licensing",
    lang: "en",
    dir: "ltr",
    title: "Licensing and Compliance | Georgia Hills",
    description: "Company licensing and operational compliance information.",
    heading: "Licensing and Compliance",
    body: "Georgia Hills operates with local tourism and transport compliance standards. Verification details and operating scope can be shared upon serious booking inquiry.",
    canonical: "https://georgiahills.com/licensing.html",
    pairedSlug: "licensing-ar",
    ctaPrimaryLabel: "Contact Team",
    ctaPrimaryHref: "/contact.html",
    ctaSecondaryLabel: "Office Details",
    ctaSecondaryHref: "/office.html"
  },
  {
    slug: "licensing-ar",
    lang: "ar",
    dir: "rtl",
    title: "الترخيص والامتثال | Georgia Hills",
    description: "معلومات ترخيص الشركة والامتثال التشغيلي في جورجيا.",
    heading: "الترخيص والامتثال",
    body: "تعمل Georgia Hills وفق معايير الامتثال المحلية لقطاع النقل والسياحة. يمكن مشاركة تفاصيل التحقق ونطاق التشغيل عند طلب حجز جاد.",
    canonical: "https://georgiahills.com/licensing-ar.html",
    pairedSlug: "licensing",
    ctaPrimaryLabel: "تواصل مع الفريق",
    ctaPrimaryHref: "/contact-ar.html",
    ctaSecondaryLabel: "تفاصيل المكتب",
    ctaSecondaryHref: "/office-ar.html"
  },
  {
    slug: "office",
    lang: "en",
    dir: "ltr",
    title: "Office Details and Contact Consistency | Georgia Hills",
    description: "Official office details, service area, and primary contact channels.",
    heading: "Office Details",
    body: "Primary base: Tbilisi, Georgia. Phone/WhatsApp: +995 579 08 85 37. Email: info@georgiahills.com. Service coverage includes Tbilisi, Kazbegi, Batumi, and major tourist corridors.",
    canonical: "https://georgiahills.com/office.html",
    pairedSlug: "office-ar",
    ctaPrimaryLabel: "Book a Trip",
    ctaPrimaryHref: "/booking.html",
    ctaSecondaryLabel: "Review Transparency",
    ctaSecondaryHref: "/reviews-policy.html"
  },
  {
    slug: "office-ar",
    lang: "ar",
    dir: "rtl",
    title: "تفاصيل المكتب ومعلومات التواصل | Georgia Hills",
    description: "تفاصيل المكتب الرسمية وقنوات التواصل الأساسية ونطاق الخدمة.",
    heading: "تفاصيل المكتب",
    body: "المقر الرئيسي: تبليسي، جورجيا. الهاتف/واتساب: +995 579 08 85 37. البريد: info@georgiahills.com. نطاق الخدمة يشمل تبليسي وكازبيجي وباتومي وأهم المسارات السياحية.",
    canonical: "https://georgiahills.com/office-ar.html",
    pairedSlug: "office",
    ctaPrimaryLabel: "احجز رحلة",
    ctaPrimaryHref: "/booking-ar.html",
    ctaSecondaryLabel: "شفافية المراجعات",
    ctaSecondaryHref: "/reviews-policy-ar.html"
  },
  {
    slug: "reviews-policy",
    lang: "en",
    dir: "ltr",
    title: "Review Source Transparency | Georgia Hills",
    description: "How customer reviews are collected, verified, and displayed.",
    heading: "Review Source Transparency",
    body: "Displayed reviews are sourced from verified customer conversations and public channels where permitted. We do not publish fabricated ratings or edited testimonials that change customer intent.",
    canonical: "https://georgiahills.com/reviews-policy.html",
    pairedSlug: "reviews-policy-ar",
    ctaPrimaryLabel: "Read Testimonials",
    ctaPrimaryHref: "/about.html",
    ctaSecondaryLabel: "Contact Team",
    ctaSecondaryHref: "/contact.html"
  },
  {
    slug: "reviews-policy-ar",
    lang: "ar",
    dir: "rtl",
    title: "شفافية مصادر المراجعات | Georgia Hills",
    description: "آلية جمع المراجعات والتحقق منها وطريقة عرضها.",
    heading: "شفافية مصادر المراجعات",
    body: "المراجعات المعروضة يتم أخذها من تواصل حقيقي مع العملاء أو قنوات عامة مسموح بها. لا نقوم بنشر تقييمات مزيفة أو تعديل الشهادات بما يغير مقصد العميل.",
    canonical: "https://georgiahills.com/reviews-policy-ar.html",
    pairedSlug: "reviews-policy",
    ctaPrimaryLabel: "تواصل مع الفريق",
    ctaPrimaryHref: "/contact-ar.html",
    ctaSecondaryLabel: "من نحن",
    ctaSecondaryHref: "/about-ar.html"
  }
];

export function getSecondaryPageBySlug(slug: string) {
  return secondaryPages.find((page) => page.slug === slug);
}
